const currencies = {
  AED: { name: "UAE Dirham", code: "AED" },
  AFN: { name: "Afghani", code: "AFN" },
  ALL: { name: "Lek", code: "ALL" },
  AMD: { name: "Armenian Dram", code: "AMD" },
  ANG: { name: "Netherlands Antillean Guilder", code: "ANG" },
  AOA: { name: "Kwanza", code: "AOA" },
  ARS: { name: "Argentine Peso", code: "ARS" },
  AUD: { name: "Australian Dollar", code: "AUD" },
  AWG: { name: "Aruban Florin", code: "AWG" },
  AZN: { name: "Azerbaijan Manat", code: "AZN" },
  BAM: { name: "Convertible Mark", code: "BAM" },
  BBD: { name: "Barbados Dollar", code: "BBD" },
  BDT: { name: "Taka", code: "BDT" },
  BGN: { name: "Bulgarian Lev", code: "BGN" },
  BHD: { name: "Bahraini Dinar", code: "BHD" },
  BIF: { name: "Burundi Franc", code: "BIF" },
  BMD: { name: "Bermudian Dollar", code: "BMD" },
  BND: { name: "Brunei Dollar", code: "BND" },
  BOB: { name: "Boliviano", code: "BOB" },
  BOV: { name: "Mvdol", code: "BOV" },
  BRL: { name: "Brazilian Real", code: "BRL" },
  BSD: { name: "Bahamian Dollar", code: "BSD" },
  BTN: { name: "Ngultrum", code: "BTN" },
  BWP: { name: "Pula", code: "BWP" },
  BYN: { name: "Belarusian Ruble", code: "BYN" },
  BZD: { name: "Belize Dollar", code: "BZD" },
  CAD: { name: "Canadian Dollar", code: "CAD" },
  CDF: { name: "Congolese Franc", code: "CDF" },
  CHE: { name: "WIR Euro", code: "CHE" },
  CHF: { name: "Swiss Franc", code: "CHF" },
  CHW: { name: "WIR Franc", code: "CHW" },
  CLF: { name: "Unidad de Fomento", code: "CLF" },
  CLP: { name: "Chilean Peso", code: "CLP" },
  CNY: { name: "Yuan Renminbi", code: "CNY" },
  COP: { name: "Colombian Peso", code: "COP" },
  COU: { name: "Unidad de Valor Real", code: "COU" },
  CRC: { name: "Costa Rican Colon", code: "CRC" },
  CUP: { name: "Cuban Peso", code: "CUP" },
  CVE: { name: "Cabo Verde Escudo", code: "CVE" },
  CZK: { name: "Czech Koruna", code: "CZK" },
  DJF: { name: "Djibouti Franc", code: "DJF" },
  DKK: { name: "Danish Krone", code: "DKK" },
  DOP: { name: "Dominican Peso", code: "DOP" },
  DZD: { name: "Algerian Dinar", code: "DZD" },
  EGP: { name: "Egyptian Pound", code: "EGP" },
  ERN: { name: "Nakfa", code: "ERN" },
  ETB: { name: "Ethiopian Birr", code: "ETB" },
  EUR: { name: "Euro", code: "EUR" },
  FJD: { name: "Fiji Dollar", code: "FJD" },
  FKP: { name: "Falkland Islands Pound", code: "FKP" },
  GBP: { name: "Pound Sterling", code: "GBP" },
  GEL: { name: "Lari", code: "GEL" },
  GHS: { name: "Ghana Cedi", code: "GHS" },
  GIP: { name: "Gibraltar Pound", code: "GIP" },
  GMD: { name: "Dalasi", code: "GMD" },
  GNF: { name: "Guinean Franc", code: "GNF" },
  GTQ: { name: "Quetzal", code: "GTQ" },
  GYD: { name: "Guyana Dollar", code: "GYD" },
  HKD: { name: "Hong Kong Dollar", code: "HKD" },
  HNL: { name: "Lempira", code: "HNL" },
  HRK: { name: "Kuna", code: "HRK" },
  HTG: { name: "Gourde", code: "HTG" },
  HUF: { name: "Forint", code: "HUF" },
  IDR: { name: "Rupiah", code: "IDR" },
  ILS: { name: "New Israeli Sheqel", code: "ILS" },
  INR: { name: "Indian Rupee", code: "INR" },
  IQD: { name: "Iraqi Dinar", code: "IQD" },
  IRR: { name: "Iranian Rial", code: "IRR" },
  ISK: { name: "Iceland Krona", code: "ISK" },
  JMD: { name: "Jamaican Dollar", code: "JMD" },
  JOD: { name: "Jordanian Dinar", code: "JOD" },
  JPY: { name: "Yen", code: "JPY" },
  KES: { name: "Kenyan Shilling", code: "KES" },
  KGS: { name: "Som", code: "KGS" },
  KHR: { name: "Riel", code: "KHR" },
  KMF: { name: "Comorian Franc", code: "KMF" },
  KPW: { name: "North Korean Won", code: "KPW" },
  KRW: { name: "Won", code: "KRW" },
  KWD: { name: "Kuwaiti Dinar", code: "KWD" },
  KYD: { name: "Cayman Islands Dollar", code: "KYD" },
  KZT: { name: "Tenge", code: "KZT" },
  LAK: { name: "Lao Kip", code: "LAK" },
  LBP: { name: "Lebanese Pound", code: "LBP" },
  LKR: { name: "Sri Lanka Rupee", code: "LKR" },
  LRD: { name: "Liberian Dollar", code: "LRD" },
  LSL: { name: "Loti", code: "LSL" },
  LYD: { name: "Libyan Dinar", code: "LYD" },
  MAD: { name: "Moroccan Dirham", code: "MAD" },
  MDL: { name: "Moldovan Leu", code: "MDL" },
  MGA: { name: "Malagasy Ariary", code: "MGA" },
  MKD: { name: "Denar", code: "MKD" },
  MMK: { name: "Kyat", code: "MMK" },
  MNT: { name: "Tugrik", code: "MNT" },
  MOP: { name: "Pataca", code: "MOP" },
  MRU: { name: "Ouguiya", code: "MRU" },
  MUR: { name: "Mauritius Rupee", code: "MUR" },
  MVR: { name: "Rufiyaa", code: "MVR" },
  MWK: { name: "Malawi Kwacha", code: "MWK" },
  MXN: { name: "Mexican Peso", code: "MXN" },
  MXV: { name: "Mexican Unidad de Inversion (UDI)", code: "MXV" },
  MYR: { name: "Malaysian Ringgit", code: "MYR" },
  MZN: { name: "Mozambique Metical", code: "MZN" },
  NAD: { name: "Namibia Dollar", code: "NAD" },
  NGN: { name: "Naira", code: "NGN" },
  NIO: { name: "Cordoba Oro", code: "NIO" },
  NOK: { name: "Norwegian Krone", code: "NOK" },
  NPR: { name: "Nepalese Rupee", code: "NPR" },
  NZD: { name: "New Zealand Dollar", code: "NZD" },
  OMR: { name: "Rial Omani", code: "OMR" },
  PAB: { name: "Balboa", code: "PAB" },
  PEN: { name: "Sol", code: "PEN" },
  PGK: { name: "Kina", code: "PGK" },
  PHP: { name: "Philippine Peso", code: "PHP" },
  PKR: { name: "Pakistan Rupee", code: "PKR" },
  PLN: { name: "Zloty", code: "PLN" },
  PYG: { name: "Guarani", code: "PYG" },
  QAR: { name: "Qatari Rial", code: "QAR" },
  RON: { name: "Romanian Leu", code: "RON" },
  RSD: { name: "Serbian Dinar", code: "RSD" },
  RUB: { name: "Russian Ruble", code: "RUB" },
  RWF: { name: "Rwanda Franc", code: "RWF" },
  SAR: { name: "Saudi Riyal", code: "SAR" },
  SBD: { name: "Solomon Islands Dollar", code: "SBD" },
  SCR: { name: "Seychelles Rupee", code: "SCR" },
  SDG: { name: "Sudanese Pound", code: "SDG" },
  SEK: { name: "Swedish Krona", code: "SEK" },
  SGD: { name: "Singapore Dollar", code: "SGD" },
  SHP: { name: "Saint Helena Pound", code: "SHP" },
  SLL: { name: "Leone", code: "SLL" },
  SOS: { name: "Somali Shilling", code: "SOS" },
  SRD: { name: "Surinam Dollar", code: "SRD" },
  SSP: { name: "South Sudanese Pound", code: "SSP" },
  STN: { name: "Dobra", code: "STN" },
  SVC: { name: "El Salvador Colon", code: "SVC" },
  SYP: { name: "Syrian Pound", code: "SYP" },
  SZL: { name: "Lilangeni", code: "SZL" },
  THB: { name: "Baht", code: "THB" },
  TJS: { name: "Somoni", code: "TJS" },
  TMT: { name: "Turkmenistan New Manat", code: "TMT" },
  TND: { name: "Tunisian Dinar", code: "TND" },
  TOP: { name: "Pa’anga", code: "TOP" },
  TRY: { name: "Turkish Lira", code: "TRY" },
  TTD: { name: "Trinidad and Tobago Dollar", code: "TTD" },
  TWD: { name: "New Taiwan Dollar", code: "TWD" },
  TZS: { name: "Tanzanian Shilling", code: "TZS" },
  UAH: { name: "Hryvnia", code: "UAH" },
  UGX: { name: "Uganda Shilling", code: "UGX" },
  USD: { name: "US Dollar", code: "USD" },
  USN: { name: "US Dollar (Next day)", code: "USN" },
  UYI: { name: "Uruguay Peso en Unidades Indexadas (UI)", code: "UYI" },
  UYU: { name: "Peso Uruguayo", code: "UYU" },
  UYW: { name: "Unidad Previsional", code: "UYW" },
  UZS: { name: "Uzbekistan Sum", code: "UZS" },
  VED: { name: "Bolívar Soberano", code: "VED" },
  VES: { name: "Bolívar Soberano", code: "VES" },
  VND: { name: "Dong", code: "VND" },
  VUV: { name: "Vatu", code: "VUV" },
  WST: { name: "Tala", code: "WST" },
  XAF: { name: "CFA Franc BEAC", code: "XAF" },
  XAG: { name: "Silver (troy ounce)", code: "XAG" },
  XAU: { name: "Gold (troy ounce)", code: "XAU" },
  XBA: {
    name: "Bond Markets Unit European Composite Unit (EURCO)",
    code: "XBA",
  },
  XBB: {
    name: "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
    code: "XBB",
  },
  XBC: {
    name: "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
    code: "XBC",
  },
  XBD: {
    name: "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
    code: "XBD",
  },
  XCD: { name: "East Caribbean Dollar", code: "XCD" },
  XDR: { name: "SDR (Special Drawing Right)", code: "XDR" },
  XOF: { name: "CFA Franc BCEAO", code: "XOF" },
  XPD: { name: "Palladium (troy ounce)", code: "XPD" },
  XPF: { name: "CFP Franc", code: "XPF" },
  XPT: { name: "Platinum (troy ounce)", code: "XPT" },
  XSU: { name: "Sucre", code: "XSU" },
  XUA: { name: "ADB Unit of Account", code: "XUA" },
  XXX: { name: "No currency", code: "XXX" },
  YER: { name: "Yemeni Rial", code: "YER" },
  ZAR: { name: "Rand", code: "ZAR" },
  ZMW: { name: "Zambian Kwacha", code: "ZMW" },
  ZWL: { name: "Zimbabwe Dollar", code: "ZWL" },
};


export default currencies